name: CI Main

on:
  push:
    branches: ["main"]
    paths:
      - "src/*"
      - "package.json"
      - ".github/workflows/cd.master.*"

jobs:
  create-release-draft:
    name: Create Release Draft

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      - name: Check package versions
        id: check_versions
        run: |
          PUBLISHED_VERSION=`npm show @oneclickdapp/ethereum-auth version`
          NEW_VERSION=`jq -r .version package.json`
          if [ "$PUBLISHED_VERSION" != "$NEW_VERSION" ];then
            echo "SHOULD_PUBLISH=1" >> $GITHUB_ENV
            echo "version changed: $PUBLISHED_VERSION -> $NEW_VERSION"
          else
            echo version unchanged: $PUBLISHED_VERSION
          fi
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"

      - name: Create release draft
        if: env.SHOULD_PUBLISH == 1
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ethereum-auth@v${{ steps.check_versions.outputs.NEW_VERSION }}
          release_name: ethereum-auth@v${{ steps.check_versions.outputs.NEW_VERSION }}
          body: |
            Changes in this Release
            ## Changed
            ## Added
            ## Fixes
            ## Breaking
          draft: true
