name: Document PR
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  label-packages:
    name: Label packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  label-size:
    name: Label PR size
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@ee2c1d869559066f4c5242f20c658e402e937e73"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
